dist: trusty
sudo: false

language: python

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27

    - python: 3.6
      env: TOXENV=py36

    - python: 3.7
      # from https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442
      dist: xenial
      sudo: true
      env: TOXENV=py37

    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=docs-localbuild

env:
  - SKIP_NETWORK_TESTS=0

install:
    - travis_retry pip install tox
script:
    - tox -e "$TOXENV"
after_success:
    - if [[ $TOXENV == 'py37' ]] ; then tox -e coveralls; else echo "No coverage to do"; fi
